In [158]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [159]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()
print(data.columns.tolist())

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']

In [160]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [161]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [162]:
#One Hot Encode Geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [163]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [164]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [165]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [166]:
#Combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [167]:
# Save the encoders and scalars
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [168]:
print(X_train)
print(y_train)

[[ 0.35649971  0.91324755 -0.6557859  ...  1.00150113 -0.57946723
  -0.57638802]
 [-0.20389777  0.91324755  0.29493847 ... -0.99850112  1.72572313
  -0.57638802]
 [-0.96147213  0.91324755 -1.41636539 ... -0.99850112 -0.57946723
   1.73494238]
 ...
 [ 0.86500853 -1.09499335 -0.08535128 ...  1.00150113 -0.57946723
  -0.57638802]
 [ 0.15932282  0.91324755  0.3900109  ...  1.00150113 -0.57946723
  -0.57638802]
 [ 0.47065475  0.91324755  1.15059039 ... -0.99850112  1.72572313
  -0.57638802]]
9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [169]:
# Divide the data set into independent and dependent features

# Independent features are everything but whether or not they exited
X = data.drop('Exited', axis=1)

# Dependent features are whether or not they exited
y = data['Exited']

# Split the data in training and testing sets, 80% of data is for training, 20% is for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale these features
# Scales features by dropping the mean and scaling to unit variance (each feature's variance is now 1) 
# Makes model faster by putting all features on the same scale
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [170]:
print(X_train)
print(y_train)

[[ 0.35649971  0.91324755 -0.6557859  ...  1.00150113 -0.57946723
  -0.57638802]
 [-0.20389777  0.91324755  0.29493847 ... -0.99850112  1.72572313
  -0.57638802]
 [-0.96147213  0.91324755 -1.41636539 ... -0.99850112 -0.57946723
   1.73494238]
 ...
 [ 0.86500853 -1.09499335 -0.08535128 ...  1.00150113 -0.57946723
  -0.57638802]
 [ 0.15932282  0.91324755  0.3900109  ...  1.00150113 -0.57946723
  -0.57638802]
 [ 0.47065475  0.91324755  1.15059039 ... -0.99850112  1.72572313
  -0.57638802]]
9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [171]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [172]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [173]:
import tensorflow as tf 
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [174]:
X_train.shape[1] #12 features per input feature

12

In [175]:
# Build our ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #HL1, connected with input layer
    Dense(32, activation='relu'), #HL2, if the input is positive, it stays the same and if it is negative it becomes 0
    Dense(1, activation='sigmoid') #output layer, transforms input values into a value between 0 and 1
])

In [176]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_18 (Dense)            (None, 64)                832

 dense_19 (Dense)            (None, 32)                2080

 dense_20 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [177]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

keras.src.losses.BinaryCrossentropy

In [178]:
# Compile the model
model.compile(optimizer=opt, loss="binary_crossentropy", metrics=['accuracy'])

In [179]:
# Set up the tensorboard to monitor loss and accuracy changes during training
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [180]:
# Set up early stopping so tht model stops if validation loss does not improve
early_stopping = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

In [181]:
# Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorflow_callback, early_stopping]
)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.3970 - accuracy: 0.8374 - val_loss: 0.3494 - val_accuracy: 0.8550
Epoch 2/100
250/250 [==============================] - 0s 706us/step - loss: 0.3556 - accuracy: 0.8558 - val_loss: 0.3466 - val_accuracy: 0.8570
Epoch 3/100
250/250 [==============================] - 0s 765us/step - loss: 0.3480 - accuracy: 0.8564 - val_loss: 0.3442 - val_accuracy: 0.8675
Epoch 4/100
250/250 [==============================] - 0s 866us/step - loss: 0.3448 - accuracy: 0.8597 - val_loss: 0.3391 - val_accuracy: 0.8590
Epoch 5/100
250/250 [==============================] - 0s 701us/step - loss: 0.3399 - accuracy: 0.8602 - val_loss: 0.3597 - val_accuracy: 0.8550
Epoch 6/100
250/250 [==============================] - 0s 696us/step - loss: 0.3375 - accuracy: 0.8604 - val_loss: 0.3575 - val_accuracy: 0.8580
Epoch 7/100
250/250 [==============================] - 0s 854us/step - loss: 0.3350 - accuracy: 0.8637 - val_loss: 0.3452 - val_accuracy: 0.8610
Epoch 8/100
250/250 [==============================] - 0s 688us/step - loss: 0.3341 - accuracy: 0.8643 - val_loss: 0.3402 - val_accuracy: 0.8625
Epoch 9/100
250/250 [==============================] - 0s 685us/step - loss: 0.3334 - accuracy: 0.8616 - val_loss: 0.3450 - val_accuracy: 0.8595
Epoch 10/100
250/250 [==============================] - 0s 766us/step - loss: 0.3296 - accuracy: 0.8665 - val_loss: 0.3625 - val_accuracy: 0.8490
Epoch 11/100
250/250 [==============================] - 0s 672us/step - loss: 0.3293 - accuracy: 0.8620 - val_loss: 0.3548 - val_accuracy: 0.8625
Epoch 12/100
250/250 [==============================] - 0s 673us/step - loss: 0.3280 - accuracy: 0.8677 - val_loss: 0.3435 - val_accuracy: 0.8615
Epoch 13/100
250/250 [==============================] - 0s 681us/step - loss: 0.3221 - accuracy: 0.8685 - val_loss: 0.3528 - val_accuracy: 0.8600
Epoch 14/100
250/250 [==============================] - 0s 694us/step - loss: 0.3224 - accuracy: 0.8681 - val_loss: 0.3476 - val_accuracy: 0.8555
Epoch 15/100
250/250 [==============================] - 0s 678us/step - loss: 0.3206 - accuracy: 0.8694 - val_loss: 0.3640 - val_accuracy: 0.8605
Epoch 16/100
250/250 [==============================] - 0s 682us/step - loss: 0.3175 - accuracy: 0.8666 - val_loss: 0.3454 - val_accuracy: 0.8570
Epoch 17/100
250/250 [==============================] - 0s 675us/step - loss: 0.3139 - accuracy: 0.8709 - val_loss: 0.3544 - val_accuracy: 0.8625
Epoch 18/100
250/250 [==============================] - 0s 685us/step - loss: 0.3164 - accuracy: 0.8690 - val_loss: 0.3522 - val_accuracy: 0.8630
Epoch 19/100
250/250 [==============================] - 0s 683us/step - loss: 0.3119 - accuracy: 0.8701 - val_loss: 0.3568 - val_accuracy: 0.8640
Epoch 20/100
250/250 [==============================] - 0s 756us/step - loss: 0.3086 - accuracy: 0.8701 - val_loss: 0.3696 - val_accuracy: 0.8515
Epoch 21/100
250/250 [==============================] - 0s 848us/step - loss: 0.3086 - accuracy: 0.8709 - val_loss: 0.3653 - val_accuracy: 0.8515
Epoch 22/100
250/250 [==============================] - 0s 927us/step - loss: 0.3000 - accuracy: 0.8749 - val_loss: 0.3679 - val_accuracy: 0.8525
Epoch 23/100
250/250 [==============================] - 0s 688us/step - loss: 0.3039 - accuracy: 0.8739 - val_loss: 0.3778 - val_accuracy: 0.8515
Epoch 24/100
250/250 [==============================] - 0s 663us/step - loss: 0.3022 - accuracy: 0.8744 - val_loss: 0.3692 - val_accuracy: 0.8575

In [182]:
model.save('model.h5')

/Users/ananya/work/myvenv/lib/python3.9/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [183]:
# Load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [184]:
%tensorboard --logdir logs/fit20250906-212028

Reusing TensorBoard on port 6011 (pid 78340), started 0:52:31 ago. (Use '!kill 78340' to kill it.)